package com.echo.audiolinkplayer.core

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import java.io.File

/**
 * Bridges the in-app WebView's cookie jar to yt-dlp's --cookies flag, so a site
 * the user has logged into themselves stays logged in during extraction.
 * Only cookies the user's own browser session produced are ever written here.
 */
object CookieStore {

    fun cookieFile(context: Context): File =
        File(context.filesDir, "cookies.txt")

    /**
     * Appends the cookies the WebView holds for [pageUrl] in Netscape format.
     * CookieManager only hands back "name=value" pairs, so domain/path/expiry are
     * filled in with sane defaults — enough for yt-dlp to replay the session.
     */
    fun captureFrom(context: Context, pageUrl: String): Int {
        val raw = CookieManager.getInstance().getCookie(pageUrl) ?: return 0
        val host = Uri.parse(pageUrl).host ?: return 0
        val domain = if (host.startsWith("www.")) host.removePrefix("www") else ".$host"
        val expiry = (System.currentTimeMillis() / 1000) + 365L * 24 * 3600

        val existing = readEntries(context).toMutableMap()
        var added = 0
        raw.split(';').forEach { pair ->
            val idx = pair.indexOf('=')
            if (idx <= 0) return@forEach
            val name = pair.substring(0, idx).trim()
            val value = pair.substring(idx + 1).trim()
            if (name.isEmpty()) return@forEach
            existing["$domain\t$name"] =
                listOf(domain, "TRUE", "/", "TRUE", expiry.toString(), name, value).joinToString("\t")
            added++
        }

        val sb = StringBuilder("# Netscape HTTP Cookie File\n# Generated by AudioLinkPlayer\n")
        existing.values.forEach { sb.append(it).append('\n') }
        cookieFile(context).writeText(sb.toString())
        return added
    }

    private fun readEntries(context: Context): Map<String, String> {
        val f = cookieFile(context)
        if (!f.exists()) return emptyMap()
        return f.readLines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .mapNotNull { line ->
                val parts = line.split('\t')
                if (parts.size < 7) null else "${parts[0]}\t${parts[5]}" to line
            }
            .toMap()
    }

    fun savedDomains(context: Context): List<String> =
        readEntries(context).keys.map { it.substringBefore('\t') }.distinct().sorted()

    fun clear(context: Context) {
        cookieFile(context).delete()
        runCatching {
            CookieManager.getInstance().removeAllCookies(null)
            CookieManager.getInstance().flush()
        }
    }
}
